Repository Vovvser/vowser-client, pull requests merged in 2025-08, with the labels that each got.

#10 Feat: JSON 응답형식 변경 - AllPaths 기반 다중 경로 처리 지원
  desktopApp/src/jvmMain/kotlin/main.kt
  desktopApp/src/jvmMain/kotlin/test.kt
  naver_website_graph.cypher
  shared/src/commonMain/kotlin/com/vowser/client/AppViewModel.kt
  shared/src/commonMain/kotlin/com/vowser/client/data/ExpandedNaverData.kt
  shared/src/commonMain/kotlin/com/vowser/client/data/GraphDataConverter.kt
  shared/src/commonMain/kotlin/com/vowser/client/data/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/navigation/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/AppBar.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/contribution/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/error/ErrorHandlingComponents.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/error/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/GraphScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/ui/theme/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/visualization/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/voice/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/websocket/BrowserControlWebSocketClient.kt
  shared/src/commonMain/kotlin/com/vowser/client/websocket/dto/AllPathsDto.kt
  shared/src/commonMain/kotlin/com/vowser/client/websocket/dto/WebSocketMessage.kt
  shared/src/commonMain/kotlin/com/vowser/client/websocket/dto/package-info.md
  shared/src/commonMain/kotlin/com/vowser/client/websocket/package-info.md
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationService.kt
Labels: enhancement, refactor

#12 Feat: UI 수정 및 라이트/다크 테마 추가
  shared/src/androidMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
  shared/src/commonMain/kotlin/App.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/AppBar.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/StatisticsPanel.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/Status.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/StatusBar.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/StatusCard.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/VoiceRecordingButton.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/contribution/ContributionModeComponents.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/error/ErrorHandlingComponents.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphCanvas.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphControls.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphLegend.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphLoading.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/ModernNetworkGraph.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/NetworkGraphComponent.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/NodeInfoPanel.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/GraphScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/SettingsScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/theme/AppTheme.kt
  shared/src/commonMain/resources/drawable/stop.png
  shared/src/commonMain/resources/drawable/subtract.png
  shared/src/iosMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
Labels: enhancement

#13 Fix: 브라우저 자동화 클릭 실패 시 스마트 네비게이션 구현 및 하이라이팅 수정
  shared/src/commonMain/kotlin/com/vowser/client/data/GraphDataConverter.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphCanvas.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserActions.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationService.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/NavigationActionExecutor.kt
Labels: bug, enhancement
