Repository Vovvser/vowser-client, pull requests merged in 2025-09, with the labels that each got.

#14 Feat: UI 수정 및 개발자 모드 추가
  shared/build.gradle.kts
  shared/src/commonMain/kotlin/App.kt
  shared/src/commonMain/kotlin/com/vowser/client/AppViewModel.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/AppBar.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/StatisticsPanel.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/StatusBar.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/StatusCard.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/contribution/ContributionModeComponents.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/error/ErrorHandlingComponents.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphCanvas.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphControls.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphHeader.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphLegend.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/GraphLoading.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/ModernNetworkGraph.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/NetworkGraphComponent.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/graph/NodeInfoPanel.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/GraphScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/SettingsScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/theme/AppTheme.kt
Labels: enhancement

#16 Feat: STT 모드 선택 UI 추가 및 WebSocket 로그 정리
  shared/src/commonMain/kotlin/App.kt
  shared/src/commonMain/kotlin/com/vowser/client/AppViewModel.kt
  shared/src/commonMain/kotlin/com/vowser/client/data/SpeechRepository.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/SttModeSelector.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/GraphScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/websocket/BrowserControlWebSocketClient.kt
Labels: feat

#17 Refactor: 대기 방식 수정, 에러 처리 최적화 및 에러 다이얼로그 추가
  shared/src/commonMain/kotlin/App.kt
  shared/src/commonMain/kotlin/com/vowser/client/AppViewModel.kt
  shared/src/commonMain/kotlin/com/vowser/client/exception/ExceptionHandler.kt
  shared/src/commonMain/kotlin/com/vowser/client/exception/VowserExceptions.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/components/ErrorDialog.kt
  shared/src/commonMain/kotlin/com/vowser/client/ui/screens/GraphScreen.kt
  shared/src/commonMain/kotlin/com/vowser/client/websocket/BrowserControlWebSocketClient.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/AdaptiveWaitManager.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationService.kt
Labels: refactor

#18 Refactor: 로깅 메시지 정리 및 기타
  desktopApp/src/jvmMain/kotlin/main.kt
  shared/src/androidMain/kotlin/com/vowser/client/AppViewModelActual.kt
  shared/src/androidMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
  shared/src/commonMain/kotlin/com/vowser/client/AppViewModel.kt
  shared/src/commonMain/kotlin/com/vowser/client/contribution/ContributionModeService.kt
  shared/src/commonMain/kotlin/com/vowser/client/contribution/ContributionModels.kt
  shared/src/commonMain/kotlin/com/vowser/client/data/SpeechRepository.kt
  shared/src/commonMain/kotlin/com/vowser/client/exception/ExceptionHandler.kt
  shared/src/commonMain/kotlin/com/vowser/client/logging/VowserLogger.kt
  shared/src/commonMain/kotlin/com/vowser/client/websocket/BrowserControlWebSocketClient.kt
  shared/src/commonMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridge.kt
  shared/src/desktopMain/kotlin/com/vowser/client/AppViewModelActual.kt
  shared/src/desktopMain/kotlin/com/vowser/client/media/MicrophoneRecorder.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/AdaptiveWaitManager.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserActions.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationService.kt
  shared/src/desktopMain/kotlin/com/vowserclient/shared/browserautomation/NavigationActionExecutor.kt
  shared/src/desktopTest/kotlin/com/vowserclient/shared/browserautomation/HighlightE2ETest.kt
  shared/src/iosMain/kotlin/com/vowser/client/AppViewModelActual.kt
  shared/src/iosMain/kotlin/com/vowserclient/shared/browserautomation/BrowserAutomationBridgeActual.kt
Labels: refactor
